/**
 * Generate ESP32 Web Assets Header
 * 
 * Converts the built frontend files into C++ header format
 * that can be stored in ESP32 flash memory (PROGMEM).
 */

async function main() {
  console.log("[esp32-assets] Generating web_assets.h...");
  
  // Read built files
  const indexHtml = await Bun.file("./dist/index.html").text();
  const mainJs = await Bun.file("./dist/assets/main.js").text();
  
  // Escape for C++ raw string literal
  // Raw literals can't contain )rawliteral" so we check for that
  if (indexHtml.includes(")rawliteral") || mainJs.includes(")rawliteral")) {
    throw new Error("Content contains raw literal delimiter - need different escaping");
  }
  
  const header = `/**
 * Web Assets Header - AUTO-GENERATED
 * 
 * Generated by: bun run scripts/generate-esp32-assets.ts
 * Do not edit manually - changes will be overwritten.
 * 
 * Contains the frontend HTML and JS as PROGMEM strings
 * stored in ESP32 flash memory.
 * 
 * Total size: ${(indexHtml.length + mainJs.length / 1024).toFixed(1)} KB
 */

#ifndef WEB_ASSETS_H
#define WEB_ASSETS_H

#include <pgmspace.h>

// index.html (${indexHtml.length} bytes)
const char INDEX_HTML[] PROGMEM = R"rawliteral(${indexHtml})rawliteral";

// main.js (${mainJs.length} bytes)  
const char MAIN_JS[] PROGMEM = R"rawliteral(${mainJs})rawliteral";

#endif
`;

  await Bun.write("./esp32/web_assets.h", header);
  
  console.log(`[esp32-assets] Generated esp32/web_assets.h`);
  console.log(`[esp32-assets]   index.html: ${indexHtml.length} bytes`);
  console.log(`[esp32-assets]   main.js: ${mainJs.length} bytes`);
  console.log(`[esp32-assets]   Total: ${((indexHtml.length + mainJs.length) / 1024).toFixed(1)} KB`);
}

main().catch((err) => {
  console.error("[esp32-assets] Error:", err);
  process.exit(1);
});

